/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        background: '#f8f9fa',
        'inverse-surface': '#2e3132',
        'on-secondary-fixed-variant': '#31447b',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#003ea8',
        'primary-fixed': '#dbe1ff',
        'secondary-container': '#acbfff',
        'primary-container': '#2563eb',
        'on-secondary-fixed': '#00174b',
        'on-secondary-container': '#394c84',
        'inverse-primary': '#b4c5ff',
        tertiary: '#943700',
        surface: '#f8f9fa',
        'on-tertiary-fixed': '#360f00',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#d9dadb',
        'secondary-fixed': '#dbe1ff',
        'surface-tint': '#0053db',
        'primary-fixed-dim': '#b4c5ff',
        'inverse-on-surface': '#f0f1f2',
        secondary: '#495c95',
        'on-error': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'on-tertiary-fixed-variant': '#7d2d00',
        primary: '#004ac6',
        'secondary-fixed-dim': '#b4c5ff',
        error: '#ba1a1a',
        'surface-container-highest': '#e1e3e4',
        'tertiary-fixed-dim': '#ffb596',
        'on-tertiary': '#ffffff',
        'surface-variant': '#e1e3e4',
        'on-primary-fixed': '#00174b',
        'on-surface': '#191c1d',
        'tertiary-fixed': '#ffdbcd',
        'on-secondary': '#ffffff',
        'on-surface-variant': '#434655',
        'on-tertiary-container': '#ffede6',
        'surface-container': '#edeeef',
        'on-primary': '#ffffff',
        'on-background': '#191c1d',
        'on-primary-container': '#eeefff',
        'surface-container-high': '#e7e8e9',
        'tertiary-container': '#bc4800',
        outline: '#737686',
        'surface-bright': '#f8f9fa',
        'outline-variant': '#c3c6d7',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
